import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "expo-router";
import { auth } from "../src/auth";
import { colors } from "../src/theme";

export default function Login() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [register, setRegister] = useState(false); const [loading, setLoading] = useState(false);
  async function continueAuth() { if (!auth) { Alert.alert("Sign in unavailable", "Firebase environment variables are not configured."); return; } setLoading(true); try { if (register) await createUserWithEmailAndPassword(auth, email.trim(), password); else await signInWithEmailAndPassword(auth, email.trim(), password); router.replace("/profile"); } catch (error) { Alert.alert("Sign in failed", error instanceof Error ? error.message : "Try again"); } finally { setLoading(false); } }
  return <SafeAreaView style={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.close}>Close</Text></Pressable><View style={styles.body}><View style={styles.mark}><Text style={styles.markText}>P</Text></View><Text style={styles.title}>{register ? "Create contributor account" : "Welcome back"}</Text><Text style={styles.subtitle}>Routing stays open to guests. Sign in only when you want to contribute and track reports.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" style={styles.input} /><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" style={styles.input} /><Pressable disabled={loading} onPress={continueAuth} style={styles.button}>{loading ? <ActivityIndicator color="white" /> : <Text style={styles.buttonText}>{register ? "Create account" : "Sign in"}</Text>}</Pressable><Pressable onPress={() => setRegister(!register)}><Text style={styles.switch}>{register ? "Already registered? Sign in" : "New contributor? Create an account"}</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper, padding: 20 }, close: { alignSelf: "flex-end", color: colors.brand, fontWeight: "700" }, body: { flex: 1, justifyContent: "center", maxWidth: 460, width: "100%", alignSelf: "center" }, mark: { width: 58, height: 58, borderRadius: 20, backgroundColor: colors.brand, alignItems: "center", justifyContent: "center" }, markText: { color: "white", fontWeight: "900", fontSize: 26 }, title: { fontSize: 30, color: colors.ink, fontWeight: "900", marginTop: 24 }, subtitle: { color: colors.muted, lineHeight: 21, marginTop: 8, marginBottom: 26 }, input: { height: 54, borderRadius: 16, backgroundColor: "white", paddingHorizontal: 16, marginBottom: 12, color: colors.ink, borderWidth: 1, borderColor: "#D7E2DD" }, button: { height: 54, backgroundColor: colors.brand, borderRadius: 17, alignItems: "center", justifyContent: "center", marginTop: 4 }, buttonText: { color: "white", fontWeight: "800" }, switch: { color: colors.brand, fontWeight: "700", textAlign: "center", marginTop: 20 } });

