import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { myReports } from "../src/api";
import { authToken, hasSession } from '../src/auth';
import { colors } from "../src/theme";
import type { RoadReport } from "../src/types";

export default function Profile() {
  const router = useRouter(); const [reports, setReports] = useState<RoadReport[]>([]); const [loading, setLoading] = useState(true); const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  useEffect(() => { hasSession().then((signedIn) => { setAuthenticated(signedIn); if (signedIn) return authToken().then(myReports).then(setReports); }).catch(() => setAuthenticated(false)).finally(() => setLoading(false)); }, []);
  if (authenticated === false) return <SafeAreaView style={styles.page}><View style={styles.empty}><Ionicons name="person-circle-outline" size={72} color={colors.brand} /><Text style={styles.title}>Contributor profile</Text><Text style={styles.muted}>Sign in to submit road photos and track their assessments.</Text><Pressable onPress={() => router.replace("/login")} style={styles.primary}><Text style={styles.primaryText}>Sign in or register</Text></Pressable><Pressable onPress={() => router.replace("/")}><Text style={styles.link}>Continue as guest</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.ink} /></Pressable><Text style={styles.headerTitle}>Your contributions</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.list}><View style={styles.hero}><Text style={styles.count}>{reports.length}</Text><Text style={styles.muted}>road reports submitted</Text></View>{loading ? <ActivityIndicator color={colors.brand} /> : reports.length === 0 ? <View style={styles.emptyCard}><Text style={styles.cardTitle}>No reports yet</Text><Text style={styles.muted}>Photograph a road surface to create your first assessment.</Text></View> : reports.map((report) => <View key={report.id} style={styles.card}><View style={styles.cardTop}><Text style={styles.cardTitle}>{report.is_demo ? "Demo observation" : "Road assessment"}</Text><Text style={styles.quality}>{Math.round(report.assessment?.road_quality ?? 0)}/100</Text></View><Text numberOfLines={2} style={styles.muted}>{report.description || "No description"}</Text><Text style={styles.date}>{new Date(report.created_at).toLocaleDateString()}</Text></View>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, header: { padding: 18, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, headerTitle: { fontWeight: "800", color: colors.ink, fontSize: 17 }, list: { padding: 18, gap: 12, maxWidth: 680, width: "100%", alignSelf: "center" }, hero: { backgroundColor: colors.brand, borderRadius: 25, padding: 24, marginBottom: 8 }, count: { color: "white", fontSize: 42, fontWeight: "900" }, muted: { color: colors.muted, lineHeight: 20 }, heroMuted: { color: "rgba(255,255,255,.75)" }, card: { padding: 18, borderRadius: 20, backgroundColor: "white", borderWidth: 1, borderColor: "#DDE7E2" }, cardTop: { flexDirection: "row", justifyContent: "space-between", marginBottom: 7 }, cardTitle: { fontWeight: "800", color: colors.ink, fontSize: 16 }, quality: { fontWeight: "900", color: colors.brand }, date: { marginTop: 9, color: colors.muted, fontSize: 11 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, title: { fontSize: 28, fontWeight: "900", color: colors.ink, marginTop: 18, marginBottom: 8 }, primary: { height: 52, borderRadius: 17, backgroundColor: colors.brand, alignItems: "center", justifyContent: "center", width: "100%", marginTop: 24 }, primaryText: { color: "white", fontWeight: "800" }, link: { color: colors.brand, fontWeight: "700", marginTop: 18 }, emptyCard: { padding: 22, borderRadius: 20, backgroundColor: "white" } });

